server:
  port: 8765

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

spring:
  application:
    name: gate
  redis:
    database: 2
    host: 10.38.77.37
    jedis:
      pool:
        max-active: 20
  rabbitmq:
    host: 10.38.77.37
    port: 5672
    username: guest
    password: guest
  sleuth:
    enabled: false
    http:
      legacy:
        enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 10.38.77.37:8848
    sentinel:
      transport:
        dashboard: 10.38.77.37:8880
    gateway:
      routes:
      - id: tag
        uri: lb://label
        predicates:
          - Path=/api/tag/**
        filters:
          - StripPrefix=2
      - id: label
        uri: lb://label
        predicates:
          - Path=/api/label/**
        filters:
          - StripPrefix=2
      - id: auth
        uri: lb://admin
        predicates:
          - Path=/api/auth/**
        filters:
          - StripPrefix=2
      - id: admin
        uri: lb://admin
        predicates:
          - Path=/api/admin/**
        filters:
          - StripPrefix=2
      - id: generator
        uri: lb://generator
        predicates:
          - Path=/api/code/**
        filters:
          - StripPrefix=1
      - id: data
        uri: lb://data
        predicates:
          - Path=/api/data/**
        filters:
          - StripPrefix=1
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true


logging:
  level:
    com.github.wxiaoqi.security.gate.v2: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env

  security:
    enabled: false


gate:
  ignore:
    startWith: /auth/jwt,/auth/captcha,/label/*


auth:
  serviceId: admin
  user:
    token-header: Authorization
  client:
    id: gate  #不填则默认读取spring.application.name
    secret: 123456


ribbon:
  eager-load:
    enabled: true
    clients: admin, label, generator
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000